<?php

use Phinx\Migration\AbstractMigration;

class Images extends AbstractMigration
{
    public function change()
    {
        $tableOptions = [
            'id' => false,
            'primary_key' => 'id',
            'comment' => 'Info of uploaded images',
            'engine' => 'InnoDB',
            'collation' => 'utf8mb4_unicode_ci',
        ];

        $posts = $this->table('images', $tableOptions);

        $posts->addColumn('id', 'biginteger', ['limit' => 20, 'signed' => false, 'identity' => true, 'comment' => 'Primary Key']);
        $posts->addColumn('name', 'string', ['limit' => 255, 'comment' => 'Upload file name']);
        $posts->addColumn('object_name', 'string', ['limit' => 255, 'comment' => 'Hash of upload file']);
        $posts->addColumn('serving_url', 'string', ['limit' => 255, 'comment' => 'The serving URL generated by Google Cloud Storage Tools']);
        $posts->addColumn('upload_time', 'datetime', ['comment' => 'File upload time']);

        $posts->create();
    }
}
